id: opecha:P000488
initial_creation_type: ocr
source_metadata:
  id: bdr:W2PD19380
  title: དགེ་རྒན་གྱི་སློབ་གསོ།
  volume:
    21ee2b932e284c56a7e2c76aa3aa05f5:
      image_group_id: I2PD20435
      title: Volume 1 of dge rgan gyi slob gso/
      volume_number: 1
      total_pages: 140
  author: ''
ebook_metadata:
  title: དགེ་རྒན་གྱི་སློབ་གསོ།
  author: ''
  sku: P000488
  cover: cover.jpg
  layers:
  - pagination
